"""
promesa_canvas.py — emits a Promesa Decision Canvas per gated ticket.
Packages an agent-ready ticket into the inputs Promesa's plan generator needs to
produce 3 divergent plans (A minimal-safe / B verify-first / C test-driven) that
the human discusses, refines, and selects.

Deterministic, reproducible. Reusable helper paired with generate_ac_rank.py.
"""
import json, datetime, re
from pathlib import Path

BASE = Path(__file__).parent
SAMPLE_PATH = BASE / "deepwiki-agent" / "sample-ac-tickets.json"
OUT_DIR = BASE / "promesa-canvases"

# Reuse the same vocabulary as generate_ac_rank.py for fences / edges / risk
FENCE_DO_NOT = ["migration", "drop column", "prod", "production", "deploy",
                "payment", "billing", "pii"]
EDGE_WORDS = ["invalid", "error", "empty", "expired", "exceed", "unauthori",
              "429", "401", "403", "duplicate", "revoked", "timeout", "concurrent"]
RISK_WORDS = ["migration", "production", "payment", "billing", "delete", "pii",
              "deploy", "purge", "drop column"]

# Keys the readiness gate marked as clearly ready (from the last run of generate_ac_rank)
# — used only to decide which tickets to scaffold when no gate file is passed.
DEFAULT_PROCESS_KEYS = {"PROJ-109", "PROJ-104"}


def normalise_ac(issue):
    ac_raw = issue.get("acceptanceCriteria", [])
    if isinstance(ac_raw, str):
        return [ac_raw]
    return list(ac_raw)


def build_canvas(issue):
    ac_list = normalise_ac(issue)
    key = issue["key"]
    all_text = " ".join(ac_list).lower()

    # fences
    do_not = sorted({w for w in FENCE_DO_NOT if w in all_text})
    # edges
    edges = sorted({w for w in EDGE_WORDS if w in all_text})
    # permissions/approvals to request
    perms = [f"Approve any {w} before execution" for w in sorted({w for w in RISK_WORDS if w in all_text})]

    # AC ids
    ac_lines = []
    for i, ac in enumerate(ac_list, 1):
        ac_lines.append(f"- **[AC-{i}]** {ac.strip()}")

    summary = issue.get("summary", "")
    # Inferred new-test intent: mention tests if AC says so
    wants_tests = "test" in all_text
    test_note_c = (
        "Add unit + integration tests before/along implementation (TDD red→green→refactor)"
        if wants_tests
        else "Introduce tests for the touched behavior even if the ticket doesn't demand them"
    )

    edges_text = ", ".join(edges) if edges else "none explicitly listed — add boundary/empty/error cases"

    m = "\n".join

    canvas = m([
        f"# Promesa Decision Canvas — {key}: {summary}",
        "",
        "> Pre-work artifact. Packages this agent-ready ticket so Promesa generates 3 divergent",
        "> plans (A/B/C) the human discusses, refines, and selects. NOT a scope expansion.",
        "",
        "## Outcome contract",
        f"- **Goal:** {summary} — deliver the observable outcome the AC below verify.",
        "",
        "## AC as decision contract",
        *ac_lines,
        "",
        "## Fences (DO / DO-NOT)",
        "- **DO:** implement exactly the behavior in the AC above; reuse existing utils/patterns.",
        *([f"- **DO-NOT:** {w}" for w in do_not] if do_not else ["- **DO-NOT:** (none flagged — keep changes contained to what the AC implies)"]),
        "",
        "## Edge & negative cases to cover",
        f"- Cover: {edges_text}",
        "",
        "## 3 strategy angles (force divergence)",
        "- **A / Minimal & safe** — smallest change, reuse existing helpers, fewest touched files, highest confidence.",
        f"- **B / Verify-first** — write guardrail/regression tests first, verify no contract regressions, then implement; {test_note_c}.",
        f"- **C / Test-driven / clean** — TDD and refactor for maintainability while satisfying every [AC-n]. {test_note_c}.",
        "",
        "## Comparison matrix (human fills Verdict)",
        "| Plan | Touched files | New tests | Regression risk | Confidence | Verdict |",
        "|------|--------------|-----------|----------------|------------|---------|",
        "| A |  |  |  |  |  |",
        "| B |  |  |  |  |  |",
        "| C |  |  |  |  |  |",
        "",
        "## Permissions / approvals to request",
        *([f"- {p}" for p in perms] if perms else ["- None flagged — Promesa may proceed within its standard permission profile."]),
        "",
        "_Generated by promesa_canvas.py (deterministic). Source: sample-ac-tickets.json_",
    ])
    return canvas


def main(process_keys=None):
    process_keys = process_keys or DEFAULT_PROCESS_KEYS
    with open(SAMPLE_PATH, encoding="utf-8") as f:
        data = json.load(f)
    OUT_DIR.mkdir(exist_ok=True)
    written = []
    for issue in data["issues"]:
        if issue["key"] in process_keys:
            canvas = build_canvas(issue)
            out = OUT_DIR / f"promesa-canvas-{issue['key']}.md"
            out.write_text(canvas, encoding="utf-8")
            written.append(str(out.resolve()))
    print(f"✅ Wrote {len(written)} canvas(es):")
    for w in written:
        print(f"   - {w}")


if __name__ == "__main__":
    main()